FROM openjdk:17-slim

WORKDIR /app

ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG AZURE_BLOB_STORAGE_CONNECTION_STRING
ARG AZURE_BLOB_STORAGE_CONTAINER_NAME
ARG AZURE_STORAGE_ACCOUNT_NAME
ARG AZURE_BLOB_STORAGE_ENDPOINT

ENV DATABASE_URL $DATABASE_URL
ENV DATABASE_USERNAME $DATABASE_USERNAME
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV AZURE_BLOB_STORAGE_CONNECTION_STRING $AZURE_BLOB_STORAGE_CONNECTION_STRING
ENV AZURE_BLOB_STORAGE_CONTAINER_NAME $AZURE_BLOB_STORAGE_CONTAINER_NAME
ENV AZURE_STORAGE_ACCOUNT_NAME $AZURE_STORAGE_ACCOUNT_NAME
ENV AZURE_BLOB_STORAGE_ENDPOINT $AZURE_BLOB_STORAGE_ENDPOINT

COPY target/ApiUsers-1.0-SNAPSHOT.jar app.jar

COPY src/main/resources/application.properties /app/src/main/resources/application.properties

EXPOSE 8080

CMD ["java", "-jar","app.jar"]
